
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8  # Updated to MySQL 8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "laravel"
            - name: MYSQL_USER
              value: "laravel_user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"  # Change this for security
  
