apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: localhost:5000/simple-registration_app  # ✅ Ensure correct image reference
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:  # ✅ Environment variables
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "laravel"
            - name: DB_USERNAME
              value: "laravel_user"
            - name: DB_PASSWORD
              value: "password"  # ⚠️ Not secure, just for testing
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: APP_KEY
              value: "base64:H2b7fzOGniGCzfQDF2DlCvTPpcU00QOoplmbP3F8SqA="
# sudo -E kubectl port-forward service/laravel  9000:9000 --address=0.0.0.0