version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    working_dir: /var/www
    ports:
      - "9000:9000"
    networks:
      - my_bridge_network

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - my_bridge_network
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent volume for MySQL
      - ./db_backup:/db_backup  # Host to container volume

networks:
  my_bridge_network:
    driver: bridge

volumes:
  mysql_data:
